### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by zigapk** [csnewman/flutter-compositor#1]
Hi there,

I'm interested in any examples or hints on how to use this library. I'm a flutter developer, however I have no experience in rust. Therefore I'd be very grateful for any advice.

Thank you very much.

**Comment by csnewman** [comment]
Hi,

I plan on including a reference compositor with the project soon. (I have one locally).

However, this project is not yet at a point where it is useable, ATM only rendering is working, and some basic input experiments. I am in the process of doing a major rewrite, however most work is happening in https://github.com/csnewman/flutter-drm and https://github.com/flutter-rs/flutter-rs. `flutter-rs` is mostly complete now. And `flutter-drm` has gained rendering, but needs input to be reimplemented. Once those are complete, I can then rewrite this library to use those.

My suggestion in the meantime is to learn some rust, ideally through using the `flutter-rs` project (you can catch me on the gitter for that repo).

**Comment by zigapk** [comment]
I had a crazy idea of trying to write a custom Flutter window manager - mostly for fun. I've once contributed to [liros](https://liri.io/) but the project more or less stalled. I've seen the [materialwm](https://github.com/csnewman/materialwm) repo and suppose your intentions are the same?

**Comment by csnewman** [comment]
Yeah, this project uses Wayland instead of X11, so the window manager is apart of the compositor.

Long term plan is `materialwm`, with a design inspired by Chrome OS and windows. Currently it looks like not much progress is being made, but most work is happening in the background.

**Comment by zigapk** [comment]
I've seen you have done quite some work in the other repos. I don't know any rust and am not confident writing it for a serious project (yet). I do have quite some experience developing flutter though - I have been using it since it was in technical preview. I've also done some linux packaging and understand some basic concepts behind wayland since liri uses it.

So if you need (and want) any help further down the line, when I can provide it, feel free to ask. I don't know if any contributions are welcome since there is no contribution guide - but I'm offering it anyway. No commitments though, since I'm still studying and working on projects at the same time. Who knows how much time I might have in half a year :stuck_out_tongue:

In case you want to contact me please write to [ziga.patacko@gmail.com](mailto:ziga.patacko@gmail.com) where we can discuss other private communication channels.

**Comment by charafau** [comment]
I actually have the same idea. Have looked at wayland and opengl compositor but I am not sure if we could just bind opengl texture to flutter one. I see that you did some work with DRM to flutter which is exciting! You could probably start with some description what you'd like to do.

Anyway, thanks for inspiration!
